baseurl = "http://techglider.in"
languageCode = "en-us"
title = "The TechGlider"
# disqusShortname = "techglider"

[permalinks]
  post = "/post/:year/:month/:day/:slug/"
  status = "/status/:year/:month/:day/:slug/"

[params]
  author = "Kartik Singhal"
