baseurl = "https://k4rtik.github.io/techglider.in/"
languageCode = "en-us"
title = "The TechGlider"
MetaDataFormat = "yaml"

[permalinks]
  post = "/post/:year/:month/:day/:slug/"
  status = "/status/:year/:month/:day/:slug/"
  quote = "/quote/:year/:month/:day/:slug/"

[params]
  author = "Kartik Singhal"
  copyright = "Copyright © 2008-2022 Kartik Singhal."
  gaCode = "UA-57213074-1"
  disqusShortname = "techglider"

[[menu.main]]
    name = "Posts"
    url = "/post"
    weight = 1
[[menu.main]]
    name = "Quotes"
    url = "/quote"
    weight = 2
[[menu.main]]
    name = "Statuses"
    url = "/status"
    weight = 3
[[menu.main]]
    name = "About"
    url = "/about"
    weight = 100
